#!/bin/sh
mkdir -p mnt/efi/boot
cp $1 mnt/efi/boot/bootx64.efi
qemu-system-x86_64 \
  -drive if=pflash,file=../../devenv/OVMF_CODE.fd \
  -drive if=pflash,file=../../devenv/OVMF_VARS.fd \
  -drive format=raw,file=fat:rw:mnt
